# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TeamsChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TeamsChat
pod 'MessageKit'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  pod 'Alamofire'
  pod 'Kingfisher'

end
